# Copyright (C) 2024 Helmar Hutschenreuter
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hutschen/mv-tool:latest
    volumes:
      - ./config.yml:/usr/src/api/config.yml
    ports:
      - '8000:8000'
    depends_on:
      - ldap
      - db

  ldap:
    image: bitnami/openldap:2.5
    environment:
      LDAP_ADMIN_USERNAME: 'admin'
      LDAP_ADMIN_PASSWORD: 'adminpasswd'
      LDAP_USERS: 'user01,user02'
      LDAP_PASSWORDS: 'passwd01,passwd02'
      LDAP_ROOT: 'dc=example,dc=org'
      LDAP_ADMIN_DN: 'cn=admin,dc=example,dc=org'
    # ports:
    #   - '1389:1389'
    volumes:
      - ldap_data:/bitnami/openldap

  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: mvtool
    # ports:
    #   - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pytest:
    build:
      context: .
      dockerfile: Dockerfile
    image: hutschen/mv-tool:latest
    volumes:
      - ./config.yml:/usr/src/api/config.yml
    entrypoint: /bin/sh
    command: -c 'pip install pytest pytest-alembic && pytest'

volumes:
  ldap_data:
  postgres_data:
